#############################################################################
# Makefile for building: nnui
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  nnui.pro
# Template: app
# Command: /home/aishwarya/Qt/5.10.0/gcc_64/bin/qmake -o Makefile nnui.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt/5.10.0/gcc_64/include -I../../Qt/5.10.0/gcc_64/include/QtQuick -I../../Qt/5.10.0/gcc_64/include/QtWidgets -I../../Qt/5.10.0/gcc_64/include/QtGui -I../../Qt/5.10.0/gcc_64/include/QtQml -I../../Qt/5.10.0/gcc_64/include/QtNetwork -I../../Qt/5.10.0/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../Qt/5.10.0/gcc_64/mkspecs/linux-g++
QMAKE         = /home/aishwarya/Qt/5.10.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/aishwarya/Qt/5.10.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/aishwarya/Qt/5.10.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = nnui1.0.0
DISTDIR = /home/aishwarya/new\ folder/nnui/.tmp/nnui1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/aishwarya/Qt/5.10.0/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/aishwarya/Qt/5.10.0/gcc_64/lib -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		backend.cpp \
		fileio.cpp qrc_qml.cpp \
		moc_backend.cpp \
		moc_fileio.cpp
OBJECTS       = main.o \
		backend.o \
		fileio.o \
		qrc_qml.o \
		moc_backend.o \
		moc_fileio.o
DIST          = images/pso.gif \
		images/ParticleSwarmArrowsAnimation.gif \
		../../Qt/5.10.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.10.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/lex.prf \
		nnui.pro backend.h \
		fileio.h main.cpp \
		backend.cpp \
		fileio.cpp
QMAKE_TARGET  = nnui
DESTDIR       = 
TARGET        = nnui


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nnui.pro ../../Qt/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/5.10.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.10.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.10.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.10.0/gcc_64/mkspecs/features/lex.prf \
		nnui.pro \
		qml.qrc \
		../../Qt/5.10.0/gcc_64/lib/libQt5Quick.prl \
		../../Qt/5.10.0/gcc_64/lib/libQt5Widgets.prl \
		../../Qt/5.10.0/gcc_64/lib/libQt5Gui.prl \
		../../Qt/5.10.0/gcc_64/lib/libQt5Qml.prl \
		../../Qt/5.10.0/gcc_64/lib/libQt5Network.prl \
		../../Qt/5.10.0/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile nnui.pro -spec linux-g++
../../Qt/5.10.0/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/5.10.0/gcc_64/mkspecs/common/unix.conf:
../../Qt/5.10.0/gcc_64/mkspecs/common/linux.conf:
../../Qt/5.10.0/gcc_64/mkspecs/common/sanitize.conf:
../../Qt/5.10.0/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/5.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/5.10.0/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/5.10.0/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/5.10.0/gcc_64/mkspecs/qconfig.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.10.0/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/5.10.0/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.10.0/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/toolchain.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/default_post.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/qt.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/resources.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/moc.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/uic.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/qmake_use.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/file_copies.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/yacc.prf:
../../Qt/5.10.0/gcc_64/mkspecs/features/lex.prf:
nnui.pro:
qml.qrc:
../../Qt/5.10.0/gcc_64/lib/libQt5Quick.prl:
../../Qt/5.10.0/gcc_64/lib/libQt5Widgets.prl:
../../Qt/5.10.0/gcc_64/lib/libQt5Gui.prl:
../../Qt/5.10.0/gcc_64/lib/libQt5Qml.prl:
../../Qt/5.10.0/gcc_64/lib/libQt5Network.prl:
../../Qt/5.10.0/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile nnui.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.10.0/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents backend.h fileio.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp backend.cpp fileio.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../Qt/5.10.0/gcc_64/bin/rcc \
		main.qml \
		images/Iris_virginica.jpg \
		images/ParticleSwarmArrowsAnimation.gif \
		images/pso.gif \
		images/iris.png \
		images/Iris_setosa.jpg \
		images/Iris_versicolor.jpg
	/home/aishwarya/Qt/5.10.0/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.10.0/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.10.0/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_backend.cpp moc_fileio.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_backend.cpp moc_fileio.cpp
moc_backend.cpp: ../../Qt/5.10.0/gcc_64/include/QtCore/QObject \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringview.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/QString \
		backend.h \
		moc_predefs.h \
		../../Qt/5.10.0/gcc_64/bin/moc
	/home/aishwarya/Qt/5.10.0/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/aishwarya/Qt/5.10.0/gcc_64/mkspecs/linux-g++ -I'/home/aishwarya/new folder/nnui' -I/home/aishwarya/Qt/5.10.0/gcc_64/include -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtQuick -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtWidgets -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtGui -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtQml -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtNetwork -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include backend.h -o moc_backend.cpp

moc_fileio.cpp: ../../Qt/5.10.0/gcc_64/include/QtCore/QObject \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringview.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		fileio.h \
		moc_predefs.h \
		../../Qt/5.10.0/gcc_64/bin/moc
	/home/aishwarya/Qt/5.10.0/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/aishwarya/Qt/5.10.0/gcc_64/mkspecs/linux-g++ -I'/home/aishwarya/new folder/nnui' -I/home/aishwarya/Qt/5.10.0/gcc_64/include -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtQuick -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtWidgets -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtGui -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtQml -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtNetwork -I/home/aishwarya/Qt/5.10.0/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include fileio.h -o moc_fileio.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.10.0/gcc_64/include/QtWidgets/QApplication \
		../../Qt/5.10.0/gcc_64/include/QtWidgets/qapplication.h \
		../../Qt/5.10.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qtguiglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qtgui-config.h \
		../../Qt/5.10.0/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringview.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qeventloop.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.10.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Qt/5.10.0/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qrgba64.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qline.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qset.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qguiapplication.h \
		../../Qt/5.10.0/gcc_64/include/QtGui/qinputmethod.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/QQmlApplicationEngine \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmlengine.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qjsengine.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qjsvalue.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qtqmlglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qtqml-config.h \
		../../Qt/5.10.0/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqml.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmlprivate.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmllist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmetaobject.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmlerror.h \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmldebug.h \
		backend.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/QObject \
		../../Qt/5.10.0/gcc_64/include/QtCore/QString \
		textfielddoublevalidator.cpp \
		../../Qt/5.10.0/gcc_64/include/QtGui/QDoubleValidator \
		../../Qt/5.10.0/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/QFile \
		../../Qt/5.10.0/gcc_64/include/QtQml/QQmlContext \
		../../Qt/5.10.0/gcc_64/include/QtQml/qqmlcontext.h \
		fileio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

backend.o: backend.cpp backend.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/QObject \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringview.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/QString \
		../../Qt/5.10.0/gcc_64/include/QtCore/QDebug \
		../../Qt/5.10.0/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qset.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backend.o backend.cpp

fileio.o: fileio.cpp fileio.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/QObject \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringview.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/QFile \
		../../Qt/5.10.0/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/QTextStream \
		../../Qt/5.10.0/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qset.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.10.0/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileio.o fileio.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_backend.o: moc_backend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_backend.o moc_backend.cpp

moc_fileio.o: moc_fileio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fileio.o moc_fileio.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/nnui/bin || mkdir -p $(INSTALL_ROOT)/opt/nnui/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/nnui/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/nnui/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/nnui/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/nnui/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

